name: Build & Deploy iOS IPA

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.1'
          channel: 'stable'
          cache: true

      - name: Install Dependencies
        run: flutter pub get

      - name: Build IPA (no codesign for Firebase)
        run: flutter build ios --release --no-codesign

      - name: Install Firebase CLI
        run: curl -sL https://firebase.tools | bash

      - name: Upload IPA to Firebase App Distribution
        run: |
          echo "${{ secrets.FIREBASE_CREDENTIALS }}" > "${HOME}/firebase-service-account.json"
          firebase appdistribution:distribute \
            build/ios/ipa/*.ipa \
            --app ${{ secrets.FIREBASE_APP_ID_IOS }} \
            --token "${{ secrets.FIREBASE_TOKEN }}" \
            --groups "testers" \
            --release-notes "Automated release from GitHub Actions"
        env:
          GOOGLE_APPLICATION_CREDENTIALS: "${HOME}/firebase-service-account.json"

      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release.ipa
          path: build/ios/ipa/*.ipa
